#version 450
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int32 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_shuffle : require
#extension GL_EXT_maximal_reconvergence : enable
#extension GL_EXT_debug_printf : enable
#extension GL_GOOGLE_include_directive : require

#include "frustum.glsl"
#include "chunk_data.glsl"
#include "neighboring_chunks.glsl"
#include "voxel_range_meshlet.glsl"
#include "voxel_mesh.glsl"

layout(local_size_x = 512, local_size_y = 1, local_size_z = 1) in;

layout(scalar, push_constant) uniform T {
    mat4 matrix;
    Frustum frustum;
    ivec3 camera_chunk_pos;
    vec3 camera_pos;
    vec3 camera_dir;
    float time;
    int debug;
    int visible_chunk_radius;
    VisibleChunksArrayRef visible_chunks;
    TmpRef tmp;
} push_constants;

struct Payload {
    uint64_t tmp;
};

shared int meshlets_counter;

int allocate_next_meshlet_idx() {
    int idx;
    if (gl_SubgroupInvocationID == 0) {
        idx = atomicAdd(meshlets_counter, 1);
    }
    idx = subgroupShuffle(idx, 0);
    return idx;
}

void main() {
    //uvec3 relative_chunk_id = gl_WorkGroupID / 4;
    //uvec3 sub_chunk = gl_WorkGroupID % 4;
    uvec3 relative_chunk_id = gl_WorkGroupID;

    int visible_chunks_array_size = push_constants.visible_chunk_radius * 2 + 1;
    uint visible_chunks_array_idx = relative_chunk_id.x * visible_chunks_array_size + relative_chunk_id.z;

    ivec3 visual_chunk_offset = ivec3(int(relative_chunk_id.x) - push_constants.visible_chunk_radius, relative_chunk_id.y, int(relative_chunk_id.z) - push_constants.visible_chunk_radius);
    ivec3 chunk_position = push_constants.camera_chunk_pos;
    chunk_position.y = 0;
    chunk_position += visual_chunk_offset;

    int section = int(relative_chunk_id.y);

    ChunkTmpRef tmp = ChunkTmpRef(uint64_t(push_constants.tmp) + 135264 * visible_chunks_array_idx + 5636 * section);
    CubicChunkRef ptr = push_constants.visible_chunks.ref[visible_chunks_array_idx].sections[section];
    if (uint64_t(ptr) != 0) {
        if (ptr.data[encode_chunkcoord(uvec3(0), 4)] == 0/* || ptr.data[encode_chunkcoord(sub_chunk, 2)] == 0*/) {
            tmp.ref.num_meshlets = 0;
            return;
        }

        uint occluded_direct_neighbors = load_neighboring_chunks(chunk_position, push_constants.camera_chunk_pos, push_constants.visible_chunk_radius, push_constants.visible_chunks);

        if (occluded_direct_neighbors < 7 || push_constants.debug == 4) {
            meshlets_counter = 0;
            barrier();

            // subgroup-coherent
            int primitives_budget = 0;
            int vertices_budget = 0;

            int num_subgroups = int(gl_WorkGroupSize.x / gl_SubgroupSize);
            int subgroup_slice = 4096 / num_subgroups;

            //int subchunk_offset = int(64 * encode_morton(sub_chunk.x, sub_chunk.y, sub_chunk.z));

            int scan_range_start = 0 + int(gl_SubgroupID.x * subgroup_slice + 0);
            int scan_range_end = 0 + int(gl_SubgroupID.x * subgroup_slice + subgroup_slice);

            int first = scan_range_start;
            int last = -1;

            for (int scan_idx = scan_range_start; scan_idx < scan_range_end; scan_idx += int(gl_SubgroupSize)) {
                ivec3 block_pos;
                decode_block_idx(scan_idx + int(gl_SubgroupInvocationID), block_pos);

                uint8_t faces = uint8_t(0);
                if (is_solid_block(block_pos)) {
                    if (!is_solid_block(block_pos + ivec3(0, 1, 0))) {
                        faces |= uint8_t(0x1);
                    }
                    if (!is_solid_block(block_pos + ivec3(0, -1, 0))) {
                        faces |= uint8_t(0x2);
                    }
                    if (!is_solid_block(block_pos + ivec3(0, 0, 1))) {
                        faces |= uint8_t(0x4);
                    }
                    if (!is_solid_block(block_pos + ivec3(0, 0, -1))) {
                        faces |= uint8_t(0x8);
                    }
                    if (!is_solid_block(block_pos + ivec3(1, 0, 0))) {
                        faces |= uint8_t(0x10);
                    }
                    if (!is_solid_block(block_pos + ivec3(-1, 0, 0))) {
                        faces |= uint8_t(0x20);
                    }
                }

                tmp.ref.faces[encode_chunkcoord(uvec3(block_pos), 0)] = faces;

                int primitives_count = bitCount(uint(faces)) * 2;
                int vertices_count = approx_unique_cube_vertices(faces);

                bool has_faces = faces != 0;

                if (subgroupAny(has_faces)) {
                    for (int i = 0; i < 8; i++) {
                        //if (num_meshlets > 100)
                        //    break;

                        int new_primitives_budget = primitives_budget + subgroupInclusiveAdd(primitives_count);
                        int new_vertices_budget = vertices_budget + subgroupInclusiveAdd(vertices_count);

                        bool over_budget = new_vertices_budget > 64 || new_primitives_budget > 126;// || ((first >= 0) && ((scan_idx + int(gl_SubgroupInvocationID)) - first) > 32);
                        if (subgroupAny(over_budget)) {
                            // the last scan iteration was under-budget but there's nothing we can add from the new one, complete it
                            if (subgroupAll(over_budget)) {

                                //if (subgroupElect())
                                //    debugPrintfEXT("meshlet %d %d has %d, %d vtx/prims in it\n", num_meshlets, scan_idx, vertices_budget, primitives_budget);

                                int meshlet_idx = allocate_next_meshlet_idx();
                                tmp.ref.meshlets[meshlet_idx] = MeshletPayload(uint16_t(first), uint16_t(scan_idx), uint16_t(vertices_budget), uint16_t(primitives_budget));
                                primitives_budget = 0;
                                vertices_budget = 0;

                                first = -1;
                            } else {
                                uint furthest_not_over_budget = subgroupBallotFindMSB(subgroupBallot(!over_budget));

                                if (gl_SubgroupInvocationID <= furthest_not_over_budget) {
                                    primitives_count = 0;
                                    vertices_count = 0;
                                }

                                //if (subgroupElect())
                                //    debugPrintfEXT("meshlet %d %d has %d, %d vtx/prims in it\n", num_meshlets, scan_idx + furthest_not_over_budget + 1, vertices_budget, primitives_budget);

                                int biggest_viable_primitive_budget = subgroupMax(over_budget ? 0 : new_primitives_budget);
                                int biggest_viable_vertices_budget = subgroupMax(over_budget ? 0 : new_vertices_budget);

                                if (first == -1) {
                                    uint first_thread_with_faces = subgroupBallotFindLSB(subgroupBallot(has_faces));
                                    first = int(scan_idx + first_thread_with_faces);
                                }

                                int meshlet_idx = allocate_next_meshlet_idx();
                                tmp.ref.meshlets[meshlet_idx] = MeshletPayload(uint16_t(first), uint16_t(scan_idx + furthest_not_over_budget + 1), uint16_t(biggest_viable_vertices_budget), uint16_t(biggest_viable_primitive_budget));
                                primitives_budget = 0;
                                vertices_budget = 0;

                                first = int(scan_idx + furthest_not_over_budget + 1);
                            }
                        } else {
                            if (first == -1) {
                                uint first_thread_with_faces = subgroupBallotFindLSB(subgroupBallot(has_faces));
                                first = int(scan_idx + first_thread_with_faces);
                            }
                            uint last_thread_with_faces = subgroupBallotFindMSB(subgroupBallot(has_faces));
                            last = int(scan_idx + last_thread_with_faces + 1);

                            primitives_budget += subgroupAdd(primitives_count);
                            vertices_budget += subgroupAdd(vertices_count);
                            break;
                        }
                    }
                }
            }

            if (primitives_budget > 0) {
                int meshlet_idx = allocate_next_meshlet_idx();
                tmp.ref.meshlets[meshlet_idx] = MeshletPayload(uint16_t(first), uint16_t(last), uint16_t(vertices_budget), uint16_t(primitives_budget));
            }

            barrier();
            tmp.ref.num_meshlets = meshlets_counter;
            return;
        }
    }

    tmp.ref.num_meshlets = 0;
}