#version 450
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int32 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require
#extension GL_KHR_shader_subgroup_basic : require
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_vote : require
#extension GL_KHR_shader_subgroup_ballot : require
#extension GL_KHR_shader_subgroup_shuffle : require
#extension GL_EXT_maximal_reconvergence : enable
#extension GL_EXT_debug_printf : enable
#extension GL_GOOGLE_include_directive : require

#include "frustum.glsl"
#include "chunk_data.glsl"
#include "neighboring_chunks.glsl"
#include "voxel_range_meshlet.glsl"
#include "voxel_mesh.glsl"

layout(local_size_x = 512, local_size_y = 1, local_size_z = 1) in;

layout(scalar, push_constant) uniform T {
    mat4 matrix;
    Frustum frustum;
    ivec3 camera_chunk_pos;
    vec3 camera_pos;
    vec3 camera_dir;
    float time;
    int debug;
    int visible_chunk_radius;
    VisibleChunksArrayRef visible_chunks;
    TmpRef tmp;
} push_constants;

struct Payload {
    uint64_t tmp;
};

VoxelMeshletsRef tmp;

#define VOXEL_RANGE_MESHLET_OUTPUT tmp.ref
#include "voxel_range_meshlet_producer.glsl"

void main() {
    uvec3 relative_chunk_id = gl_WorkGroupID;

    int visible_chunks_array_size = push_constants.visible_chunk_radius * 2 + 1;
    uint visible_chunks_array_idx = relative_chunk_id.x * visible_chunks_array_size + relative_chunk_id.z;

    ivec3 visual_chunk_offset = ivec3(int(relative_chunk_id.x) - push_constants.visible_chunk_radius, relative_chunk_id.y, int(relative_chunk_id.z) - push_constants.visible_chunk_radius);
    ivec3 chunk_position = push_constants.camera_chunk_pos;
    chunk_position.y = 0;
    chunk_position += visual_chunk_offset;

    int section = int(relative_chunk_id.y);

    tmp = VoxelMeshletsRef(uint64_t(push_constants.tmp) + 135264 * visible_chunks_array_idx + 5636 * section);

    CubicChunkRef ptr = push_constants.visible_chunks.ref[visible_chunks_array_idx].sections[section];
    if (uint64_t(ptr) != 0) {
        if (ptr.data[encode_chunkcoord(uvec3(0), 4)] == 0/* || ptr.data[encode_chunkcoord(sub_chunk, 2)] == 0*/) {
            tmp.ref.num_meshlets = 0;
            return;
        }

        uint occluded_direct_neighbors = load_neighboring_chunks(chunk_position, push_constants.camera_chunk_pos, push_constants.visible_chunk_radius, push_constants.visible_chunks);

        if (occluded_direct_neighbors < 7 || push_constants.debug == 4) {
            scan_chunk_produce_meshlets();
            return;
        }
    }

    tmp.ref.num_meshlets = 0;
}